version: "3.8"
services:
  strapi:
    image: strapi/strapi:3.1.5
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    restart: unless-stopped
    volumes:
      - ./backend:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    restart: unless-stopped
    volumes:
      - .mongodb:/data/db
    ports:
      - "27017:27017"

  extraleicht:
    container_name: extraleicht
    image: extraleicht
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: unless-stopped
    depends_on:
      - strapi
